# Generated by Django 3.2.3 on 2021-06-21 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('company', models.CharField(max_length=255)),
                ('mobile', models.IntegerField(max_length=12)),
                ('city', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'employee',
            },
        ),
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('email', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=255)),
                ('last_name', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('address', models.TextField()),
                ('date_of_birth', models.DateField()),
                ('company', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'manager',
            },
        ),
    ]
